sudo: required
services: 
    - docker

before_install:
    - docker build -t marijusjenulis/docker-react -f Dockerfile.dev .

script :
    - docker run -e CI=true marijusjenulis/docker-react npm run test